name: Build, Push & Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code with full history & tags
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Java
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: gradle

      # Build JAR
      - name: Build with Gradle
        run: ./gradlew clean build -x test

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Bump version & create tag
      - name: Bump version and push tag
        id: bump
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          INITIAL_VERSION: 0.0.1

      # Create GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump.outputs.new_tag }}
          name: Release ${{ steps.bump.outputs.new_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with version + latest
      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tirania_bot:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tirania_bot:${{ steps.bump.outputs.new_tag }}
          login: true
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Update build.gradle to next SNAPSHOT
      - name: Set next snapshot version
        run: |
          NEXT_VERSION=$(echo "${{ steps.bump.outputs.new_tag }}" | awk -F. '{printf "%d.%d.%d", $1, $2, $3+1}')
          sed -i "s/^version = .*/version = \"${NEXT_VERSION}-SNAPSHOT\"/" build.gradle
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -am "Bump version to ${NEXT_VERSION}-SNAPSHOT [skip ci]"
          git push
