name: Build, Push & Release

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pr-checks:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    outputs:
      bump-type: ${{ steps.set-bump.outputs.bump }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: gradle

      - name: Check PR has release label
        id: check-label
        run: |
          echo "PR labels: ${{ toJSON(github.event.pull_request.labels) }}"
          LABELS_JSON='${{ toJSON(github.event.pull_request.labels) }}'
          if ! echo "$LABELS_JSON" | grep -qE '"name":\s*"(release:patch|release:minor|release:major)"'; then
            echo "Error: Pull request must have one of the labels: release:patch, release:minor, release:major"
            exit 1
          fi

      - name: Build and test
        run: ./gradlew clean build

      - name: Check code format
        run: ./gradlew spotlessCheck

      - name: Run SpotBugs
        run: ./gradlew spotbugsMain

      - name: Build Docker image (PR validation)
        run: docker build -t test-image .

  release:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine release bump
        id: bump
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
           COMMIT_MSG=$(git log -1 --pretty=%B)
           echo "Commit message: $COMMIT_MSG"
           if echo "$COMMIT_MSG" | grep -q "BREAKING CHANGE"; then
             echo "bump=major" >> $GITHUB_OUTPUT
           elif echo "$COMMIT_MSG" | grep -qiE "^feat"; then
             echo "bump=minor" >> $GITHUB_OUTPUT
           else
             echo "bump=patch" >> $GITHUB_OUTPUT
           fi

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: ${{ steps.bump.outputs.BUMP }}
          INITIAL_VERSION: 0.0.1

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          name: Release ${{ steps.tag.outputs.new_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set release version in build.gradle
        run: |
          TAG=${{ steps.tag.outputs.new_tag }}
          TAG=${TAG#v}
          sed -i "s/^version = .*/version = \"$TAG\"/" build.gradle
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -am "Set release version $TAG [skip ci]"
          git push

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tirania_bot:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tirania_bot:${{ steps.tag.outputs.new_tag }}

      - name: Set next snapshot version
        run: |
          TAG=${{ steps.tag.outputs.new_tag }}
          TAG=${TAG#v}
          NEXT_VERSION=$(echo "$TAG" | awk -F. '{printf "%d.%d.%d", $1,$2,$3+1}')
          sed -i "s/^version = .*/version = \"${NEXT_VERSION}-SNAPSHOT\"/" build.gradle
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -am "Bump version to ${NEXT_VERSION}-SNAPSHOT [skip ci]"
          git push
