name: Build, Push & Release

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pr-checks:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check PR has release label
        if: github.event_name == 'pull_request'
        run: |
          echo "PR labels: ${{ toJSON(github.event.pull_request.labels) }}"
          LABELS_JSON='${{ toJSON(github.event.pull_request.labels) }}'
          if ! echo "$LABELS_JSON" | grep -qE '"name":\s*"(release:patch|release:minor|release:major)"'; then
            echo "Error: Pull request must have one of the labels: release:patch, release:minor, release:major"
            exit 1
          fi

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: gradle

      - name: Build and test
        run: ./gradlew clean build

      - name: Check code format
        run: ./gradlew spotlessCheck

      - name: Run SpotBugs
        run: ./gradlew spotbugsMain

      - name: Build Docker image (PR validation)
        run: docker build -t test-image .

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: []

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: gradle

      - name: Determine bump type from PR labels
        id: bump-type
        run: |
          BUMP=patch
          if ${{ contains(github.event.pull_request.labels.*.name, 'release:minor') }}; then
            BUMP=minor
          elif ${{ contains(github.event.pull_request.labels.*.name, 'release:major') }}; then
            BUMP=major
          fi
          echo "BUMP=$BUMP" >> $GITHUB_ENV
          echo "Bump type: $BUMP"

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Bump version and push tag
        id: bump
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: ${{ env.BUMP }}
          INITIAL_VERSION: 0.0.1

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump.outputs.new_tag }}
          name: Release ${{ steps.bump.outputs.new_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tirania_bot:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tirania_bot:${{ steps.bump.outputs.new_tag }}

      - name: Set next snapshot version
        run: |
          NEXT_VERSION=$(echo "${{ steps.bump.outputs.new_tag }}" | awk -F. '{printf "%d.%d.%d", $1, $2, $3+1}')
          sed -i "s/^version = .*/version = \"${NEXT_VERSION}-SNAPSHOT\"/" build.gradle
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -am "Bump version to ${NEXT_VERSION}-SNAPSHOT [skip ci]"
          git push
